Implementar dark mode #14
devpt-org/site pull request #16
Opened 2023-02-04 20:24 UTC by Unisergius

O darkmode usa o vueuse/core.

no Welcome.vue é definido as cores que depois são herdadas pela estrutura fora.

Se for preciso mais paginas, será importante fazer isto no layout?

2023-02-04 20:25 UTC, Unisergius commented
Importante dar uma olhadela no NavBar.vue porque ainda sou uma beca nabo em estabelecer as declaracoes certas do export e como é usado no componente. 

Obrigado

2023-02-21 09:48 UTC, IvoPereira requested changes
Em relação ao código fiz só umas pequenas anotações, mas pareceu-me bem :+1: 

No entanto antes de aprovar queria testar a funcionalidade, mas precisava que fizesses merge com `main`. Se precisares de ajuda pinga-me no Discord!

2023-02-21 09:48 UTC, IvoPereira commented on resources/js/Components/NavBar/NavBar.vue
> +                <img v-show="!this.dark" class="h-8 w-auto" :src="'images/logo-blue.svg'" />
Nesta situação podemos passar diretamente a prop para a tag `img`. Por norma os [bind props são passadas quando não estás a passar strings](https://vuejs.org/guide/components/props.html#prop-passing-details) (números, funções, etc).

```suggestion
                <img v-show="this.dark" class="h-8 w-auto" src="images/logo-blue-white.svg" />
                <img v-show="!this.dark" class="h-8 w-auto" src="images/logo-blue.svg" />
```

2023-02-21 09:48 UTC, IvoPereira commented on resources/js/Components/NavBar/NavBar.vue
> +            <img class="block lg:hidden h-8 w-auto"  :src="'images/logo-mini-blue.svg'" />
Aqui podemos passar diretamente também:

```suggestion
            <img class="block lg:hidden h-8 w-auto"  src="images/logo-mini-blue.svg" />
```

2023-02-21 09:48 UTC, IvoPereira commented on resources/js/Components/NavBar/NavBar.vue
> +            <img class="block lg:hidden h-8 w-auto"  :src="'images/logo-mini-blue.svg'" />
Aqui podemos passar diretamente também:

```suggestion
            <img class="block lg:hidden h-8 w-auto"  src="images/logo-mini-blue.svg" />
```

2023-02-21 09:48 UTC, IvoPereira commented on resources/js/Components/NavBar/NavBar.vue
> +            <a class="btn btn-ghost btn-circle" @click="toggleDark()">
Quando não precisamos de passar nenhuma variável de nenhum contexto externo, podemos simplificar e passar simplesmente o nome do callback (on click).

```suggestion
            <a class="btn btn-ghost btn-circle" @click="toggleDark">
```

2023-02-21 09:48 UTC, IvoPereira commented on resources/js/Components/NavBar/NavBar.vue
> +                <MoonIcon v-show="this.dark" width="20" height="20" />
Aqui poderíamos usar um `v-else`. Na situação em si far-me-ia sentido não usarmos (isto é, deixarmos como está) pois envolve outras alterações - muda o src da `img` por exemplo).

```suggestion
                <MoonIcon v-show="this.dark" width="20" height="20" />
                <SunIcon v-else width="20" height="20" />
```

O que te parece?

2023-02-21 09:48 UTC, IvoPereira commented on resources/js/Pages/Welcome.vue
>  defineProps({
```suggestion
import NavBar from '@/Components/NavBar/NavBar.vue'

defineProps({
```

2023-02-21 09:48 UTC, IvoPereira commented on resources/js/Pages/Welcome.vue
>  </template>
A indentação aqui parece-me estar um pouco fora de sítio. Podes verificar?

2023-02-27 23:20 UTC, Unisergius commented on resources/js/Pages/Welcome.vue
>  </template>
Não estou a perceber aqui as sugestões. Podes-me ajudar a compreender? Queres que eu colapse o conteudo das divs que estao abaixo do HeroLogo?

2023-03-04 20:40 UTC, Unisergius commented
Qual o plano em relação a este PR?

2023-03-04 20:43 UTC, Unisergius commented on resources/js/Pages/Welcome.vue
>  </template>
Tendo em conta que agora temos o MainLayout, talvez isto não se aplica exatamente assim.

2023-05-04 19:24 UTC, IvoPereira approved these changes
Obrigado pela contribuição @Unisergius! Demorou mas finalmente foi aprovado :)

Pode ainda precisar de uns ajustes mas revemos num próximo PR caso necessário.

2023-05-04 19:24 UTC, merged