Readme.md
devpt-org/site pull request #4
Opened 2022-12-26 12:06 UTC by sergiofresco

Criei instruções para a instalação do projeto na maquina local de quem queira contribuir.

Adicionado comandos de npm

2022-12-26 20:53 UTC, IvoPereira requested changes
Hey Sérgio! Obrigado pela contribuição :+1: 

Fiz uns pequenos ajustes mais para uniformizar a pessoa na qual se explica a documentação. Diz-me o que achas e caso não concordes com algo.

Idealmente seria interessante depois termos dividido por pequenas categorias (Instalação, workflow de desenvolvimento, boas práticas, contribuição, etc), mas por agora um pequeno README.md com o que enviaste acho que já ajuda imenso. Bom trabalho! :+1:

2022-12-26 20:53 UTC, IvoPereira commented on README.md
> +Clonar o projeto na tua maquina
```suggestion
Clonar o projeto na máquina
```

2022-12-26 20:53 UTC, IvoPereira commented on README.md
> +Ir para a diretoria do projeto
```suggestion
Entrar na pasta do projeto
```

2022-12-26 20:53 UTC, IvoPereira commented on README.md
> +Duplicar o ficheiro .env.example para .env e alterar os dados se necessário.
```suggestion
Duplicar o ficheiro `.env.example` para `.env` e alterar os dados se necessário.
```

2022-12-26 20:53 UTC, IvoPereira commented on README.md
> +Adicionar a propriedade APP_PORT para mudares a porta se a porta 80 já estiver
Sugeria passar isto para um "heading" de edgecases ou mesmo FAQs? P.ex.

## FAQs

### Recebo um erro que a porta está em uso.
...

### Ao tentar executar o `sail` recebo um erro que diz que o `docker` não está em execução.
...

---

O que achas?

2022-12-26 20:53 UTC, IvoPereira commented on README.md
> +Correr o servidor localmente
```suggestion
Executar o Sail para executar todos os serviços necessários
```

2022-12-26 20:53 UTC, IvoPereira commented on README.md
> +Para finalizar, na raiz do teu projeto no terminal corre o seguinte comando:
```suggestion
Para abrir o projeto, no navegador abrir o endereço
`http://localhost` (ou `http://localhost:PORTA onde PORTA corresponde à porta que possa ter sido configurado mais acima. Por pré-definição é a 80).

Para realizar a compilação em real-time dos recursos de JavaScript+CSS, executar o seguinte comando:
```

2022-12-27 09:32 UTC, sergiofresco commented on README.md
> +Adicionar a propriedade APP_PORT para mudares a porta se a porta 80 já estiver
Por mim na boa, só acho que é provavel pessoas já terem algo a ser servido na porta 80

2022-12-27 10:03 UTC, IvoPereira commented on README.md
> +Adicionar a propriedade APP_PORT para mudares a porta se a porta 80 já estiver
Sim, é bastante possível. A sugestão aqui é mais para organizarmos num capítulo de FAQs, porque concordo com a sugestão.

Consegues alterar este então?

2022-12-27 11:27 UTC, ijpatricio commented
Olá @sergiofresco ! Mt obrigado pela disponibilidade.
Deixei uma review em alguns pontos, validas, pf?
Thanks!

2022-12-27 11:46 UTC, sergiofresco commented
Huh, @ijpatricio ajuda-me. Onde posso ver a review? :S

2022-12-28 20:27 UTC, IvoPereira requested changes
Fora os comments que me enviei só retirava os commits referentes à Navbar e enviava no respetivo PR.

Um dos objetivos do repo e melhores práticas que queremos seguir inclui também enviarmos apenas as alterações referentes ao escopo do PR.

Achas que conseguias?

Fora isso e os comments que enviei acima parece-me ok 👍 alguma sugestão @ijpatricio?

2022-12-28 20:27 UTC, IvoPereira commented on README.md
> +laravel sail. Para teres o daemon a correr manualmente:
```suggestion
Certifica-te que tens o docker daemon a correr antes de lançar o servidor pelo Laravel Sail. Para teres o daemon a correr manualmente:
```

2022-12-28 20:27 UTC, IvoPereira commented on README.md
> +a ser usada. Aqui usamos 8080 por exemplo mas pode ser outra.
```suggestion
Adiciona a propriedade APP_PORT para mudares a porta se a porta 80 já estiver a ser usada. No projeto usamos 8080 por exemplo mas pode ser outra
```

2022-12-28 20:27 UTC, IvoPereira commented on README.md
> +Duplicar o ficheiro `.env.example` para `.env` e alterar os dados se necessário.
```suggestion
Duplicar o ficheiro `.env.example` para `.env` e alterar os dados se necessário
```

2022-12-28 20:59 UTC, ijpatricio commented
Concordo @IvoPereira , o PR ficou com scope creep 😄 

No entanto, podemos assumir o merge, uma vez que assumo eu fazer as afinações. Faço isto para que o @sergiofresco tb não se desmotive. para meter alterações a Front e Back num PR de `README.md` é porque não está habituado, e pronto, está com um tamanho que assumo fazer o "reconcile". 👍 

Não vamos poder fazer sempre disto, claro! 😄

2022-12-28 21:42 UTC, IvoPereira commented
> No entanto, podemos assumir o merge, uma vez que assumo eu fazer as afinações.

Nesse caso @sergiofresco vamos aceitar o merge assim e o @ijpatricio assim que possível faz as afinações necessárias :smile: 

Bom trabalho :+1:

2022-12-28 21:43 UTC, IvoPereira approved these changes

2022-12-28 21:43 UTC, merged